### ISSUE TITLE
org.json.JSONException: Value <!DOCTYPE of type java.lang.String cannot be converted to JSONObject

### ISSUE THREAD

**Issue by Dimoshka** [Dimoshka/JWP#27]
``` bash
org.json.JSONException: Value <!DOCTYPE of type java.lang.String cannot be converted to JSONObject
at org.json.JSON.typeMismatch(JSON.java:111)
at org.json.JSONObject.<init>(JSONObject.java:158)
at org.json.JSONObject.<init>(JSONObject.java:171)
at ua.pp.dimoshka.classes.f.b(SourceFile:290)
at ua.pp.dimoshka.classes.ae.a(SourceFile:198)
at ua.pp.dimoshka.classes.ae.doInBackground(SourceFile:79)
at android.os.AsyncTask$2.call(AsyncTask.java:287)
at java.util.concurrent.FutureTask.run(FutureTask.java:234)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
at java.lang.Thread.run(Thread.java:838)
org.json.JSONException: Value <!DOCTYPE of type java.lang.String cannot be converted to JSONObject
at org.json.JSON.typeMismatch(JSON.java:111)
at org.json.JSONObject.<init>(JSONObject.java:158)
at org.json.JSONObject.<init>(JSONObject.java:171)
at ua.pp.dimoshka.classes.f.b(SourceFile:290)
at ua.pp.dimoshka.classes.ae.a(SourceFile:198)
at ua.pp.dimoshka.classes.ae.doInBackground(SourceFile:79)
at android.os.AsyncTask$2.call(AsyncTask.java:287)
at java.util.concurrent.FutureTask.run(FutureTask.java:234)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
at java.lang.Thread.run(Thread.java:838)

```

**Comment by nikhilgodhani08** [comment]
HI, me also getting this error .. so, any solution for this?
